version: '2'

services:
  app:
    image: 'acheron1232/prod:1.0'
    container_name: app
    depends_on:
      - db
    ports:
      - "443:443"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_SECURITY_DOMAIN=https://sabaody.org

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
#    volumes:
#      - db_data:/var/lib/postgresql/data
#
#volumes:
#  db_data: